export const RECEIVE_ESSAY = "RECEIVE_ESSAY";
export const RECEIVE_MY_ESSAY = "RECEIVE_MY_ESSAY";
export const REMOVE_MY_ESSAY = "REMOVE_MY_ESSAY";
export const RECEIVE_ESSAY_DETAIL = "RECEIVE_ESSAY_DETAIL";
